# format v2
version: '2'

# services
services:
  # fluentd that is rescived from fluentd logger
  fluentd:
    build: fluent
    ports:
      - "24224:24224"
  # simple http server application. logs are collect with fluentd logger plugin.
  goweb-comp:
    build: go-web
    ports:
      - "8001:8000"
    logging:
      driver: fluentd
      options:
        fluentd-address: "localhost:24224"
        fluentd-tag: "docker.{{.FullID}}"
    depends_on:
      - fluentd
